### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by axeberg** [chas-academy/08-weather-app-aminoaarab#1]
@aminoaarab  make sure to mention me when you close this issue to indicate that this has been deployed and is ready for grading.

**Comment by aminoaarab** [comment]
Deployed Now @axelolsson

**Comment by axeberg** [comment]
@aminoaarab I need a fallback solution for when the user presses "Block" in the browser when asked for location.

A simple error message is fine.

**Comment by aminoaarab** [comment]
@axelolsson "Block" - error message updated and deployed
